# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8334c7609a5d6f02ef69382d88c139bf5deff7d1a887937df84f9f3d9a5e63c4448ccf6410e8287310448d294c36b7f08d6e09e34e1a5310258a9f3164b131e

test:
  secret_key_base: 96427a2e263e2e87e226cbbb7120684eac23e2ae57ba0a631ef4a79059052fd3b2c4c257e8258dee1b1962f64c86330cafffb2b68dcd58e74ea42011002aa284

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
